######################################################################
# Automatically generated by qmake (3.0) ?????? ?????? 8 03:06:17 2017
######################################################################

TEMPLATE = app
TARGET = Test_App
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
greaterThan(QT_MAJOR_VERSION, 4) {
    QT *= widgets
} else {
}
